### ISSUE TITLE
Organizationの移譲について

### ISSUE THREAD

**Issue by gorockn** [Auriga-rodev/Auriga#2]
下記Organization、リポジトリが重複しているため、Organizationの移譲をさせていただきたいのですが、質問はこちらでよろしかったでしょうか？

https://github.com/auriga/auriga

**Comment by poporing-popori** [comment]
@gorockn 
> 質問はこちらでよろしかったでしょうか？
大丈夫です！

Organization移譲の件ですが、可能であれば是非お願いします！
移譲はOwner権限をいただけるということですか？

**Comment by gorockn** [comment]
@poporing-popori 

>大丈夫です！

ありがとうございます。

>Organization移譲の件ですが、可能であれば是非お願いします！
>移譲はOwner権限をいただけるということですか？

はい。そのように考えています。
手前味噌のGitコンバートスクリプトを使い、Gitで差分管理をしていましたが
公式がGithubに移られたのであれば、混乱を避ける意味でもOnwer移譲が適切と考えます。

移譲にあたり、どなたに移譲すれば良いのか、アカウント名を提示頂ければ幸いです。
よろしくお願いします。

**Comment by poporing-popori** [comment]
@gorockn 
返信ありがとうございます〜。

> 公式がGithubに移られたのであれば、混乱を避ける意味でもOnwer移譲が適切と考えます。

ありがとうございます、ではOwner移譲をさせていただきたく存じます。


> 移譲にあたり、どなたに移譲すれば良いのか、アカウント名を提示頂ければ幸いです。
> よろしくお願いします。

一旦、私に付与していただければと。
お手数ですがよろしくお願いします:innocent:

**Comment by gorockn** [comment]
@poporing-popori 
お世話になっております。

> ありがとうございます、ではOwner移譲をさせていただきたく存じます。

こちらこそ断りもいれずにお手間おかけしました。

> 一旦、私に付与していただければと。

先程Onwer権限付きでInviteさせていただきました。
ご査収ください。よろしくお願いします。

**Comment by poporing-popori** [comment]
@gorockn 
invitationの確認 & Acceptいたしました。
ありがとうございました！

> こちらこそ断りもいれずにお手間おかけしました。

いえいえ、そもそも今時VCSで管理すらしていなかった事が問題だったと思います(Unified形式のdiffで管理て・・・)。
今までミラーリングしていただき助かった人も多いかと存じます、本当にありがとうございましたｍｍ

移譲していただいたOrganizationは好きに使っても良いという認識で合っていますでしょうか。
早速ですが、レポジトリの引っ越しを行おうと考えておりまして。

**Comment by gorockn** [comment]
@poporing-popori 
お心遣い、ありがとうございます。

> 移譲していただいたOrganizationは好きに使っても良いという認識で合っていますでしょうか。

はい、好きに使っていただいて構いません。
元のリポジトリも削除していただいて結構です。
こちらで行う作業が特にないようであればこちらのIssueも閉じて頂ければと思います。
お騒がせして申し訳ありませんでした。よろしくお願いします。

**Comment by poporing-popori** [comment]
@gorockn 承知いたしました！
それではこちらのIssueはcloseします。
ありがとうございました！
